### ISSUE TITLE
RemoteDb isn't compatible with the built-in MongoDB REST API

### ISSUE THREAD

**Issue by slang800** [mWater/minimongo#17]
...is it supposed to be used with some other REST API?

**Comment by grassick** [comment]
It's a custom REST API that met our needs, not the official one (I didn't even know an official one existed, and we needed PATCH capability anyway).

Very simple: GET (selector, limit, skip, sort as query parameters). POST (to insert), PATCH (to upsert), DELETE. See the tests for details.

**Comment by slang800** [comment]
Is the code for this custom one available anywhere?

**Comment by grassick** [comment]
Alas, it's not. We are now actually using PostgreSQL as a back end with a translation layer.
