### ISSUE TITLE
setting up hybrid db

### ISSUE THREAD

**Issue by nostalgicdodo** [mWater/minimongo#21]
hi,

I have a database on a server and I'm trying to recreate what meteor does; a local db on the browser that syncs bi-directionally with the one on the server.
how do I set this up? I looked at the source code yet I'm unsure what to pass to the url, client and httpClient parameters for the remoteDb constructor. could you provide example code for this scenario? I'm unable to infer this just from reading the docs.

thanks

**Comment by grassick** [comment]
Hello, I've added some docs to the README.md. Let me know if this doesn't make it clear enough.

---

Example code:

```
remoteDb = new minimongo.RemoteDb("http://someserver.com/api/", "myclientid123")
```

This would create a remote db that would make the following call to the api for a find to collection abc:

`GET http://someserver.com/api/abc?client=myclientid123`

The client is optional and is a string that is passed in each call only to make authentication easier.
