### ISSUE TITLE
in hybridDb, by default it fetch all fields from remoteDb and cache them. wish to change this behavior

### ISSUE THREAD

**Issue by beeplin** [mWater/minimongo#31]
in hybridDb code we see: 
```
      # If caching, get all fields
      if options.cacheFind
        delete remoteOptions.fields
```
but sometimes we need to fetch a list from remoteDb, which has loooooooots of items but just includes `_id` and `name` fields. we need to cache it, so `cacheFind` option has to be true. But we don't need the other fields. actually the other fields might be very huge and it's impossible to fetch logs of items all at once.

@grassick would you please consider change this behavior, or at least give a new option to turn this off?

**Comment by grassick** [comment]
If I were to build in partial caching, it would mean that the current contents of the local database could not be trusted as they would be a hodgepodge of partial records from all previous partial queries.

However, I believe that you can easily accomplish what you are trying to do: do a query with cacheFind false and then manually cache them yourself. Just call `cache` on the local database (yourdb.localDb) to cache the rows that you want to keep. Be sure to pass in the same selector that you used for the original query.

**Comment by beeplin** [comment]
got it. a good design indeed! thanks!
