### ISSUE TITLE
Meteor.Collection.ObjectID definition

### ISSUE THREAD

**Issue by mathew-kurian** [mWater/minimongo#33]
Where is the following defined https://github.com/mWater/minimongo/blob/87593b150d02321781c676bed48476d8e942bfd3/src/selector.js#L374?

**Comment by grassick** [comment]
Oops! It isn't... feel free to remove in a pull request...

**Comment by yanickrochon** [comment]
Has this been solved?

**Comment by grassick** [comment]
It has now!
