### ISSUE TITLE
utils.autoselectLocalDb() requires an example

### ISSUE THREAD

**Issue by BananaAcid** [mWater/minimongo#38]
trying out how it works, I ended up with this:
`
    var localDb;
    var useless_something = minimongo.utils.autoselectLocalDb({namespace: "myDb"}, function(localDb_init) {
        localDb = localDb_init;
    }, function() { alert("some error!"); });
`

**Comment by grassick** [comment]
I added a comment to the readme about how to use it!

**Comment by BananaAcid** [comment]
I saw that comment, but I could not figure out how to use it. Took me an hour, examining the return and the callback values as well as the source code, and figuring out, how to use it in place of the `new IndexedDb` in the example. An example, of the intended use would be great. I am sorry, I didn't mean to offend you.
