### ISSUE TITLE
LocalStorageDb.removeCollection() removes all keys from namespace

### ISSUE THREAD

**Issue by islandlinux** [mWater/minimongo#42]
To reproduce:

1. create two collections using `LocalStorageDb` and add documents to each of them, e.g. `test1` and `test2`
1. call `removeCollection()` 
1. all keys matching the namespace are removed

I have fixed the issue in my forked branch:

https://github.com/islandlinux/minimongo/commit/2096c8d542d8a59b5df977d998366496f715a516

**Comment by grassick** [comment]
Thanks for fixing this! I've merged and published!
