### ISSUE TITLE
collection.remove() not removing from IndexedDB

### ISSUE THREAD

**Issue by Crispioso** [mWater/minimongo#47]
Hi,

Sorry if this isn't a code issue but I'm a bit stuck.

I'm having an issue with removing doc(s) from a database backed by IndexedDB. I've noticed that minimongo is setting the 'state' property to 'removed' in the database, it's not actually being removed.

Thanks in advance!

**Comment by grassick** [comment]
Ya, it keeps a copy so that the changes can be sent to a server. Use `resolveRemove(id, success, error)` to fully remove it after you've done a `remove`

**Comment by Crispioso** [comment]
Great, thank you!
