### ISSUE TITLE
Cannot read property 'findOne' of undefined with HybridDB

### ISSUE THREAD

**Issue by yanickrochon** [mWater/minimongo#63]
I'm not quite sure how to setup and use HybridDb instances. So far, I have

```js
const localDb = new minimongo.IndexedDb({ namespace: "foo" }, () => {
  // ..
}, error => {
   console.error('Could not create local db instance');
   console.error(error);
});

const remoteDb = new minimongo.RemoteDb(`${API_ROOT}/api/`, 'foo');

const db = new minimongo.HybridDb(localDb, remoteDb)

// ... some time later

db.addCollection('bananas');

db.bananas.findOne({ id: 123 }).then(banana => console.log("**** banana:123", banana));
```

But I get an error about `banana` being undefined on localDb. I'm not sure what's the purpose of HybridDb.addCollection?

**Comment by grassick** [comment]
You'll need to add the collection `bananas` to the local and remote dbs first, then add it to the hybrid db.

**Comment by yanickrochon** [comment]
Please, add this to the docs?

**Comment by yanickrochon** [comment]
You're closing issues without ever considering them!

```js
localDb.addCollection('bananas');
remoteDb.addCollection('bananas');
db.addCollection('bananas');

localDb.bananas.findOne({ id: 10 }, {}, banana => console.log(banana));
// -> null     (ok)
localDb.bananas.find({}, {}).fetch(bananas => console.log(bananas));
// -> []      (ok)

remoteDb.bananas.findOne({ id: 10 }, {}, banana => console.log(banana));
// -> { id: 10, name: 'banana' }
remoteDb.bananas.find({}, {}).fetch(bananas => console.log(bananas));
// -> [ { id: 10, name: 'banana' } ]

db.bananas.findOne({ id: 10 }, {}, role => console.log(role));
// Uncaught DOMException: Failed to execute 'get' on 'IDBObjectStore': The parameter is not a valid key.
db.bananas.find({}, {}).fetch(roles => console.log("*** ROLES", roles));
// Uncaught null
```

**Comment by grassick** [comment]
I'm quite responsive to reviewing and merging pull requests, so please feel welcome to make one and I'll have a look! My schedule is quite full, so I generally don't add features unless they are needed by one of my clients or are implemented in a pull request.

**Comment by yanickrochon** [comment]
That one is an error, not a feature. And... why is this project in CoffeeScript?

**Comment by grassick** [comment]
The docs do say:

> Be sure to add the same collections to all three databases (local, hybrid and remote).

On a separate note, please remember that you're asking for volunteer work on a package that is working just fine for us. I know that tone sometimes gets lots in text, but yours felt both critical and demanding.

This is a clone of Mongo functionality, so you need to use `_id` rather than `id`. 

Finally, if you have a particular bit of code that really doesn't work, I'd be willing to look at it in an online code sandbox as a favor to you.
