### ISSUE TITLE
Support CORS?

### ISSUE THREAD

**Issue by yanickrochon** [mWater/minimongo#64]
If the remote database needs to be accessed with specific HTTP headers, for example `credentials`, etc. How do I pass this when creating a RemoteDb instance?

**Comment by grassick** [comment]
You'll need to pass in a third parameter to the RemoteDb, `httpClient` which then does the call the way that you want it to. You'll need to implement something similar to `jQueryHttpClient`.

**Comment by yanickrochon** [comment]
Instead of closing this, would be nice to actually implement this internally.
