### ISSUE TITLE
[docs] Specify that `client` arg is required for Hybrid use

### ISSUE THREAD

**Issue by j6k4m8** [mWater/minimongo#70]
Calling `HybridDb#upload` fails with the (imo cryptic) error message, 

```
Client required to upsert
```

The documentation currently doesn't mention that `upload` requires that the `RemoteDb` has a `client` argument specified, though this appears to be the fix:

#### Broken:

```js
let client = new minimongo.MemoryDb();
let remote = new minimongo.RemoteDb(MY_URL)

client.addCollection("animals");
remote.addCollection("animals");

let db = new minimongo.HybridDb(client, remote);
db.addCollection("animals");

// Later:
db.upload();
```

#### Working:

```js
let client = new minimongo.MemoryDb();
let remote = new minimongo.RemoteDb(MY_URL, "foo") // ← here's the fix

client.addCollection("animals");
remote.addCollection("animals");

let db = new minimongo.HybridDb(client, remote);
db.addCollection("animals");

// Later:
db.upload();
```

I think this is just a simple docs fix; or possibly I'm missing something obvious! Thought it was worth mentioning :)

**Comment by grassick** [comment]
Good catch! I've removed the requirement to have a client when doing an upsert in the latest version (6.6.1)
