### ISSUE TITLE
Comparission to https://pouchdb.com/

### ISSUE THREAD

**Issue by Doogiemuc** [mWater/minimongo#75]
I really like your aproach. Would it be possible that you could say something about the differences between minimongo and PouchDB.

Obviously MiniMongo is smaller, which can be a great advantage on lightweight clients, such as mobile phones.

Anything else? Pros and Cons.   Thank you for your support.

**Comment by grassick** [comment]
I'm afraid that I've never looked into PouchDB, so I can't be much help!
