### ISSUE TITLE
Key $v must not start with '$'

### ISSUE THREAD

**Issue by carlosalvidrez** [mWater/minimongo#80]
Hoping you can shed some light into this error message if by change you have ever seen it... it only happens in PROD, so I can't really troubleshoot it much. My app is in Meteor 2.4 and connecting to Mongo Atlas 5.0.3... 

`**Exception in flushing DDP buffered writes: MinimongoError: Key $v must not start with '$'**`

Thanks!

**Comment by grassick** [comment]
This is not the minimongo used in Meteor, but a standalone offshoot. Better to go to Meteor's github!
