### ISSUE TITLE
Improvement on RemoteDb docs

### ISSUE THREAD

**Issue by thomscoder** [mWater/minimongo#85]
Hellooo, I'm using the minimongo package and it's dope. I'm working with the minimongo.IndexedDB and I find quite easy to work with.

What I find really hard to use is the RemoteDb feature.
Say I have a node server at `localhost:5000` and a local MongoDb instance at `mongodb://localhost:27017`

How do I configure the remoteDb to work with that instance?

```js
const db = new minimongo.RemoteDb("http://localhost:5000/api/", this.userId, _, true, true)
db.addCollection("scratch")
db.collections["scratch"].upsert(...)
```

doesn't work. Also my server is never reached and in the network tab there's no request.

What am I doing wrong?

**Comment by grassick** [comment]
That's really strange! Are you waiting for the upsert to be completed? e.g. either `db.collections["scratch"].upsert(somedoc).then(success => { ... })` or `db.collections["scratch"].upsert(somedoc, onSuccess, onError)`? If so, are either success or error called?

**Comment by thomscoder** [comment]
Hi @grassick thanks for the quick reply,

this is my code
```js
import minimongo from "minimongo";
import { db } from "../App";
import store from '../store';

export default class HybridDB {
  constructor() {
    this.userId = store.getState().auth.user.id;
    this.remoteDb = new minimongo.RemoteDb("http://localhost:5000/api/", this.userId, _, true, true)
    this.db = new minimongo.HybridDb(db, this.remoteDb)
  }

  addCollection() {
    this.remoteDb.addCollection("scratch");
    this.remoteDb.collections['scratch'].upsert({msg: "hello world"}, success => console.log("UPSERTED!"), err => new Error(err))

    return {
      rdb: {
        db: this.remoteDb,
        collections: this.remoteDb.collections,
      }
    }
  }
} 
```

The `addCollection()` returns this
<img width="830" alt="image" src="https://user-images.githubusercontent.com/78874117/203078816-6fd25df1-d324-45fe-8c05-5dd5290c0aa8.png">

But the server is never reached, neither the success or the error callbacks are called and no collection is created in my MongoDB :(
The indexedDB works really smoothly.

**Comment by grassick** [comment]
You're passing in `_` as the 3rd argument of RemoteDb. That parameter is only for overriding the default http client. In this context, I'm not sure what that is defined as.

Here's a sandbox that demonstrates that the connection is attempted: https://codesandbox.io/s/heuristic-ride-tuegug?file=/src/index.js

I'm afraid that's all the support I can give. Hope this helps and good luck!

**Comment by thomscoder** [comment]
> You're passing in `_` as the 3rd argument of RemoteDb. That parameter is only for overriding the default http client. In this context, I'm not sure what that is defined as.
> 
> Here's a sandbox that demonstrates that the connection is attempted: https://codesandbox.io/s/heuristic-ride-tuegug?file=/src/index.js
> 
> I'm afraid that's all the support I can give. Hope this helps and good luck!

It worked magnificently! 
It was that underscore lol
Thank you very much!!!

**Comment by thomscoder** [comment]
Sorry to bother you one more time @grassick 
Could you tell me how to use the `usePostFind` ?

Where do I have to put the `/find` parameter to use the POST method in the find request?

**Comment by grassick** [comment]
POST find is only used when the GET is larger than 500 characters. There's currently no way to force it to use it each time. If you pass in true as the 5th argument of the constructor of RemoteDb, it will use POST when that condition is met.

**Comment by thomscoder** [comment]
You saved me an hour of trial and errors. thank you!
