### ISSUE TITLE
db.collection.remove doesn't actually remove the data from indexedDB?

### ISSUE THREAD

**Issue by inovramadani** [mWater/minimongo#86]
I can see the document has "removed" state. But will this be ever removed actually from indexedDB at some point in time? If not, then how to remove it? As this will pile up unneeded data on the indexedDB.

![image](https://user-images.githubusercontent.com/27492820/209417221-a046a841-a2bb-48be-93e8-35add9e972bf.png)

**Comment by grassick** [comment]
I've added docs to explain how to resolve removes. We keep them around so that they can be sent to the server if this is used in a client/server arrangement. See section "Resolving removes" of the README.md
